### ISSUE TITLE
flaws

### ISSUE THREAD

**Issue by anton-latyshonok** [bergomaniaq/practiceBSU#4]

**Comment by ghost** [comment]
At least one POST request should be tried (the answer from the service could describe rejection)

**Comment by anton-latyshonok** [comment]
update

**Comment by julia-murashko** [comment]
Hi! Cool :)

Some comments according to Task 4 (to raise your mark up):

- Twitter API
- Your JSON files are results of requests. You have to download and add postman collection of session JSON files.

Feel free to do your best!

**Comment by ghost** [comment]
Resolved in a #7 Thanks!
